### ISSUE TITLE
Add more descriptive text on front page.

### ISSUE THREAD

**Issue by whyrusleeping** [protocol/websites#9]
We should grab a bit more from the paper intro, and have something like:

IPFS is a new hypermedia distribution protocol, addressed by content and
identities. IPFS enables the creation of completely distributed applications.
It aims to make the web faster, safer, and more open.  In some ways IPFS is
similar to the web, but IPFS could be seen as a single giant bittorrent swarm
exchanging git objects. IPFS provides a high throughput content addressed block
storage system, with content addressed hyperlinks. This forms a generalized
Merkle DAG, a data structure upon which one can build versioned file systems,
blockchains, and even a Permanent Web. IPFS combines a distributed hashtable,
an incentivized block exchange, and a self-certifying namespace. IPFS has no
single point of failure, and nodes do not need to trust each other.

IPFS is an open source project developed by the team at Interplanetary Networks
and many contributors from the open source community.

**Comment by jbenet** [comment]
This is already there just needs to be published



—

**Comment by jbenet** [comment]
done
